const bootScreen=document.getElementById('bootScreen'),introScreen=document.getElementById('introScreen'),modeScreen=document.getElementById('modeScreen'),desktop=document.getElementById('desktop'),bootProgress=document.getElementById('bootProgress'),bootPercent=document.getElementById('bootPercent'),windowsLayer=document.getElementById('windowsLayer'),systemTime=document.getElementById('systemTime'),modeLabel=document.getElementById('modeLabel');
const apps={
 settings:{title:'Settings',width:590,height:440,content:`<div class="window-body"><h2>System Settings</h2><div class="settings-grid"><div class="setting-tile"><strong>Appearance</strong><small>Theme: Monochrome</small></div><div class="setting-tile"><strong>Personalization</strong><small>Accent: Silver</small></div><div class="setting-tile"><strong>Notifications</strong><small>Focus mode enabled</small></div><div class="setting-tile"><strong>Privacy & Security</strong><small>Protected browsing</small></div><div class="setting-tile"><strong>Network</strong><small>Vindrell Wi‑Fi connected</small></div><div class="setting-tile"><strong>Sound</strong><small>Output: Default</small></div><div class="setting-tile"><strong>Accessibility</strong><small>Motion and text controls</small></div><div class="setting-tile"><strong>System Updates</strong><small>VindrellOS is up to date</small></div></div></div>`},
 movies:{title:'Movies/TV',width:520,height:360,content:`<div class="window-body"><h2>Movie Library</h2><div class="window-grid"><div class="window-card"><strong>Featured</strong><span>Midnight Run</span></div><div class="window-card"><strong>Series</strong><span>Signal Fade</span></div><div class="window-card"><strong>Genres</strong><span>Drama</span></div><div class="window-card"><strong>Queue</strong><span>12 Items</span></div></div></div>`},
 browser:{title:'DuckDuckGo Browser',width:680,height:440,content:`<div class="browser-view"><div class="browser-toolbar"><button id="browserBack">←</button><button id="browserForward">→</button><div id="addressBar" class="address-bar">https://duckduckgo.com</div></div><div class="browser-page"><div><div class="duck-logo">🦆</div><h2>DuckDuckGo</h2><p>Private searching in Vindrell Browser.</p><form id="searchForm" class="search-box"><input id="searchInput" placeholder="Search DuckDuckGo" autocomplete="off"><button>Search</button></form><p id="searchStatus"></p></div></div></div>`},
 games:{title:'Games',width:620,height:470,content:`<div class="window-body runner-body"><h2>School Break Arcade</h2><p>Quick, offline-friendly games for a short break.</p><div class="game-list"><button class="game-link" data-game="runner">Vindrell Runner</button><button class="game-link" data-game="memory">Memory Match</button><button class="game-link" data-game="reaction">Reaction Test</button></div><div id="gameStage"></div></div>`},
 files:{title:'Files',width:500,height:330,content:`<div class="window-body"><h2>Files</h2><div class="window-grid"><div class="window-card"><strong>Work</strong><span>Projects</span></div><div class="window-card"><strong>Media</strong><span>Library</span></div><div class="window-card"><strong>System</strong><span>Logs</span></div><div class="window-card"><strong>Archive</strong><span>Backups</span></div></div></div>`},
 finder:{title:'Finder',width:460,height:300,content:`<div class="window-body"><h2>Desktop</h2><p>Welcome back to VindrellOS. Your workspace is ready.</p></div>`}
};
function setTime(){systemTime.textContent=new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});}function chooseMode(mode){desktop.classList.toggle('windows-mode',mode==='windows');modeLabel.textContent=mode==='windows'?'Windows experience':'macOS experience';document.getElementById('menuBrand').textContent=mode==='windows'?'Start':'Finder';modeScreen.classList.add('hidden');desktop.classList.remove('hidden');}
function openApp(name){const app=apps[name];if(!app)return;const el=document.createElement('div');el.className='window';el.style.left=`${Math.random()*18+18}%`;el.style.top=`${Math.random()*14+18}%`;el.style.width=`${app.width}px`;el.style.height=`${app.height}px`;el.innerHTML=`<div class="window-header"><div class="window-dots"><span></span><span></span><span></span></div><div class="window-title">${app.title}</div><div></div></div>${app.content}`;windowsLayer.appendChild(el);windowsLayer.style.pointerEvents='auto';if(name==='browser')wireBrowser(el);if(name==='games')wireGames(el);}
function wireBrowser(el){const form=el.querySelector('#searchForm'),input=el.querySelector('#searchInput'),status=el.querySelector('#searchStatus'),address=el.querySelector('#addressBar');form.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(!q)return;status.textContent=`Searching DuckDuckGo for “${q}”…`;address.textContent=`https://duckduckgo.com/?q=${encodeURIComponent(q)}`;window.open(`https://duckduckgo.com/?q=${encodeURIComponent(q)}`,'_blank','noopener');});}
function wireGames(el){el.querySelectorAll('[data-game]').forEach(b=>b.addEventListener('click',()=>{const stage=el.querySelector('#gameStage');if(b.dataset.game==='runner'){stage.innerHTML='<p>Runner loaded. Use the Games app runner controls here.</p><button class="runner-start" id="runnerLaunch">Start Runner</button>';el.querySelector('#runnerLaunch').onclick=()=>startRunner(stage);}else if(b.dataset.game==='memory'){stage.innerHTML='<p>Memory Match: remember the sequence.</p><button class="runner-start" onclick="this.textContent=\'Nice memory!\'">Start</button>';}else{stage.innerHTML='<p>Reaction Test: click when the panel changes.</p><button class="runner-start" onclick="this.textContent=\'Great reaction!\'">Start</button>';}});});}
function startRunner(stage){stage.innerHTML='<canvas class="runner-canvas" width="540" height="170"></canvas><button class="runner-start">Jump / Restart</button>';const c=stage.querySelector('canvas'),ctx=c.getContext('2d'),btn=stage.querySelector('button');let x=70,vy=0,ob=520,run=false,score=0,last=0;function jump(){if(!run||x===70){run=true;vy=-430;}}function frame(t){let dt=Math.min((t-last)/1000,.04);last=t;ctx.clearRect(0,0,c.width,c.height);vy+=1200*dt;const y=Math.max(0,130-(25+vy*dt));if(y===0)vy=0;ob-=220*dt;if(ob<-25){ob=540;score++;}ctx.fillStyle='#eee';ctx.fillRect(0,145,540,2);ctx.fillRect(x,y,25,25);ctx.fillStyle='#888';ctx.fillRect(ob,112,22,33);if(ob<x+25&&ob+22>x&&y+25>112){run=false;ctx.fillStyle='#fff';ctx.fillText('Game over — press restart',180,30)}else{ctx.fillStyle='#aaa';ctx.fillText(`Score: ${score}`,12,20);requestAnimationFrame(frame)}}btn.onclick=()=>{x=70;ob=520;score=0;run=true;last=performance.now();requestAnimationFrame(frame)};c.onpointerdown=jump;}
function startBoot(){let p=0;const i=setInterval(()=>{p+=Math.random()*18+8;if(p>=100){p=100;clearInterval(i);setTimeout(()=>{bootScreen.classList.add('hidden');introScreen.classList.remove('hidden')},350)}bootProgress.style.width=`${p}%`;bootPercent.textContent=`${Math.floor(p)}%`},140)}
document.getElementById('introContinue').onclick=()=>{introScreen.classList.add('hidden');modeScreen.classList.remove('hidden')};document.querySelectorAll('.mode-option').forEach(b=>b.onclick=()=>chooseMode(b.dataset.mode));document.querySelectorAll('.app-icon,.app-button').forEach(b=>b.onclick=()=>openApp(b.dataset.app));setTime();setInterval(setTime,15000);startBoot();
